Repository exercism/wren, pull requests merged in 2024-02, with the labels that each got.

#172 roman-numerals: sync
  exercises/practice/roman-numerals/.docs/instructions.md
  exercises/practice/roman-numerals/.docs/introduction.md
  exercises/practice/roman-numerals/.meta/config.json
Labels: x:size/tiny

#175 Normalize practice exercise names
  config.json
Labels: x:rep/tiny

#176 Discuss concurrency vs parallelism, taking inspiration from javascript
  exercises/practice/parallel-letter-frequency/.docs/instructions.append.md
Labels: x:rep/small
